repos:
  # Formatador de código - clang-format
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.6  # Última versão estável
    hooks:
      - id: clang-format
        stages: [commit]
        types_or: [c++]
        args: [--style=Google, -i]  # Estilo Google, formata no lugar

  # Linter - clang-tidy
#  - repo: https://github.com/pocc/pre-commit-hooks
#    rev: v1.3.5
#    hooks:
#      - id: clang-tidy
#        args: [-fix , -p=build]
#        types_or: [c++]
        # Remova additional_dependencies

  # Verificador de formatação CMake
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format

  # Verificador de trailing whitespace
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        types_or: [c++]
      - id: end-of-file-fixer
        types_or: [c++]
      - id: check-yaml
      - id: check-added-large-files